# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74ffdfdf0fc1e64826b845e3137e44acdd44ee584f622277c518900f60f1d4a95ca96f68e0023ab5c081ab4d0e7b38b65b36149c5e2aa34a96c12a1be5bbc5bb

test:
  secret_key_base: 02edcf6e2da025a8f4291b660d7d5b3949bfd0fedaabf0670c9e6b33e3868fe4e118122ec1ad0828814394de22cb94c937f7ce15d3ad9a17ea849963361ff197

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 74ffdfdf0fc1e64826b840293452452cdd44ee584f622277c518900f60f1d4a95ca96f68e0023ab5c081ab4d0e7b38b65b36149c5e2aa34a96c12a1be5bbc5bb
